In [1]:
import pandas as pd
import numpy as np

In [2]:
!ls

Analisis Movimientos.ipynb
Analisis_PVD.ipynb
Articulos.csv
Articulos_PT.csv
Funciones.ipynb
MITO.ipynb
Movimientos.csv
SAis_vendidos_2022.ipynb
Sais_vendidos_2020.csv

In [4]:
df = pd.read_csv('./Movimientos.csv', sep=';',encoding='latin')

In [5]:
df.head()

,Referencia,Cantidad con signo,Entradas,Salidas,Cantidad Abonada,Precio,Importe,Existencia,Precio medio,Valor Inventario,...,Fecha Factura,Serie Factura,Codigo Presupuesto,Codigo Comercial,Empresa Emisora,Pedido Web,Referencia Proveedor,Referencia Fabricante,Codigo Tarifa,Nombre Tarifa
0,PH 9210,-1,0,1,0,"227,19","227,19",243,"120,40","29259,55",...,2-01-2018,1,NaN,516,3,No,1PE-C001401-00G,FRIGATE 1000VA/800W,6,NPVD
1,PH 9210,11,11,0,0,"120,40","-1324,40",243,"120,40","29259,55",...,3-01-2018,2,NaN,527,3,No,1PE-C001401-00G,FRIGATE 1000VA/800W,6,NPVD
2,PH 9210,-10,0,10,0,"120,40","1204,00",243,"120,40","29259,55",...,3-01-2018,2,NaN,527,3,No,1PE-C001401-00G,FRIGATE 1000VA/800W,6,NPVD
3,PH 9210,-1,0,1,0,"227,19","227,19",241,"120,40","29018,64",...,4-01-2018,1,NaN,516,3,Si,1PE-C001401-00G,FRIGATE 1000VA/800W,6,NPVD
4,PH 9210,-1,0,1,0,"227,19","227,19",240,"120,40","28898,23",...,9-01-2018,1,NaN,527,3,Si,1PE-C001401-00G,FRIGATE 1000VA/800W,6,NPVD

In [6]:
df.dtypes

Referencia               object
Cantidad con signo        int64
Entradas                  int64
Salidas                   int64
Cantidad Abonada          int64
Precio                   object
Importe                  object
Existencia                int64
Precio medio             object
Valor Inventario         object
Escalón de precio         int64
Codigo Cliente            int64
Codigo Factura           object
Codigo Pedido            object
Fecha Pedido             object
Hora Pedido              object
Fecha Factura            object
Serie Factura             int64
Codigo Presupuesto       object
Codigo Comercial          int64
Empresa Emisora           int64
Pedido Web               object
Referencia Proveedor     object
Referencia Fabricante    object
Codigo Tarifa             int64
Nombre Tarifa            object
dtype: object

In [7]:
df[['Entradas', 'Salidas', 'Cantidad Abonada', 'Cantidad con signo', 'Existencia', 'Escalón de precio']].astype('int64')

,Entradas,Salidas,Cantidad Abonada,Cantidad con signo,Existencia,Escalón de precio
0,0,1,0,-1,243,1
1,11,0,0,11,243,1
2,0,10,0,-10,243,3
3,0,1,0,-1,241,1
4,0,1,0,-1,240,1
...,...,...,...,...,...,...
2261,0,1,0,-1,79,1
2262,0,1,0,-1,78,1
2263,0,10,0,-10,68,3
2264,0,1,0,-1,64,1
2265,0,2,0,-2,64,1

In [8]:
df.dtypes

Referencia               object
Cantidad con signo        int64
Entradas                  int64
Salidas                   int64
Cantidad Abonada          int64
Precio                   object
Importe                  object
Existencia                int64
Precio medio             object
Valor Inventario         object
Escalón de precio         int64
Codigo Cliente            int64
Codigo Factura           object
Codigo Pedido            object
Fecha Pedido             object
Hora Pedido              object
Fecha Factura            object
Serie Factura             int64
Codigo Presupuesto       object
Codigo Comercial          int64
Empresa Emisora           int64
Pedido Web               object
Referencia Proveedor     object
Referencia Fabricante    object
Codigo Tarifa             int64
Nombre Tarifa            object
dtype: object

In [9]:
df.isna().sum()

Referencia                  0
Cantidad con signo          0
Entradas                    0
Salidas                     0
Cantidad Abonada            0
Precio                      0
Importe                     0
Existencia                  0
Precio medio                0
Valor Inventario            0
Escalón de precio           0
Codigo Cliente              0
Codigo Factura             29
Codigo Pedido              10
Fecha Pedido               10
Hora Pedido                10
Fecha Factura              29
Serie Factura               0
Codigo Presupuesto       2222
Codigo Comercial            0
Empresa Emisora             0
Pedido Web                 10
Referencia Proveedor        0
Referencia Fabricante     743
Codigo Tarifa               0
Nombre Tarifa               0
dtype: int64

In [10]:
df.columns

Index(['Referencia', 'Cantidad con signo', 'Entradas', 'Salidas',
       'Cantidad Abonada', 'Precio', 'Importe', 'Existencia', 'Precio medio',
       'Valor Inventario', 'Escalón de precio', 'Codigo Cliente',
       'Codigo Factura', 'Codigo Pedido', 'Fecha Pedido', 'Hora Pedido',
       'Fecha Factura', 'Serie Factura', 'Codigo Presupuesto',
       'Codigo Comercial', 'Empresa Emisora', 'Pedido Web',
       'Referencia Proveedor', 'Referencia Fabricante', 'Codigo Tarifa',
       'Nombre Tarifa'],
      dtype='object')

In [11]:
df["Precio"] = df["Precio"].str.replace(',','.')

In [12]:
df["Importe"] = df["Importe"].str.replace(',','.')

In [13]:
df["Precio medio"] = df["Precio medio"].str.replace(',','.')

In [14]:
df["Valor Inventario"] = df["Valor Inventario"].str.replace(',','.')

In [15]:
df.dtypes

Referencia               object
Cantidad con signo        int64
Entradas                  int64
Salidas                   int64
Cantidad Abonada          int64
Precio                   object
Importe                  object
Existencia                int64
Precio medio             object
Valor Inventario         object
Escalón de precio         int64
Codigo Cliente            int64
Codigo Factura           object
Codigo Pedido            object
Fecha Pedido             object
Hora Pedido              object
Fecha Factura            object
Serie Factura             int64
Codigo Presupuesto       object
Codigo Comercial          int64
Empresa Emisora           int64
Pedido Web               object
Referencia Proveedor     object
Referencia Fabricante    object
Codigo Tarifa             int64
Nombre Tarifa            object
dtype: object

In [16]:
df.isna().sum()

Referencia                  0
Cantidad con signo          0
Entradas                    0
Salidas                     0
Cantidad Abonada            0
Precio                      0
Importe                     0
Existencia                  0
Precio medio                0
Valor Inventario            0
Escalón de precio           0
Codigo Cliente              0
Codigo Factura             29
Codigo Pedido              10
Fecha Pedido               10
Hora Pedido                10
Fecha Factura              29
Serie Factura               0
Codigo Presupuesto       2222
Codigo Comercial            0
Empresa Emisora             0
Pedido Web                 10
Referencia Proveedor        0
Referencia Fabricante     743
Codigo Tarifa               0
Nombre Tarifa               0
dtype: int64

In [17]:
df[['Precio', 'Importe', 'Precio medio', 'Valor Inventario']] = df[['Precio', 'Importe', 'Precio medio', 'Valor Inventario']].astype('float')

In [18]:
df.dtypes

Referencia                object
Cantidad con signo         int64
Entradas                   int64
Salidas                    int64
Cantidad Abonada           int64
Precio                   float64
Importe                  float64
Existencia                 int64
Precio medio             float64
Valor Inventario         float64
Escalón de precio          int64
Codigo Cliente             int64
Codigo Factura            object
Codigo Pedido             object
Fecha Pedido              object
Hora Pedido               object
Fecha Factura             object
Serie Factura              int64
Codigo Presupuesto        object
Codigo Comercial           int64
Empresa Emisora            int64
Pedido Web                object
Referencia Proveedor      object
Referencia Fabricante     object
Codigo Tarifa              int64
Nombre Tarifa             object
dtype: object

In [29]:
df['Codigo Factura'].isna()

0       False
1       False
2       False
3       False
4       False
        ...
2261    False
2262    False
2263    False
2264    False
2265    False
Name: Codigo Factura, Length: 2266, dtype: bool

In [27]:
df.loc[df['Codigo Factura'].isna()]

,Referencia,Cantidad con signo,Entradas,Salidas,Cantidad Abonada,Precio,Importe,Existencia,Precio medio,Valor Inventario,...,Fecha Factura,Serie Factura,Codigo Presupuesto,Codigo Comercial,Empresa Emisora,Pedido Web,Referencia Proveedor,Referencia Fabricante,Codigo Tarifa,Nombre Tarifa
277,PH 9210,-1,0,1,0,295.00,295.00,0,122.82,0.00,...,NaN,22,NaN,54985,4,No,1PE-C001401-00G,FRIGATE 1000VA/800W,6,NPVD
384,PH 9210,-1,0,1,0,193.39,193.39,0,95.94,0.00,...,NaN,22,NaN,54985,4,No,1PE-C001401-00G,FRIGATE 1000VA/800W,6,NPVD
400,PH 9210,-1,0,1,0,193.39,193.39,0,95.94,0.00,...,NaN,22,NaN,54985,4,No,1PE-C001401-00G,FRIGATE 1000VA/800W,6,NPVD
402,PH 9210,-1,0,1,0,193.39,193.39,0,95.94,0.00,...,NaN,22,NaN,54985,4,No,1PE-C001401-00G,FRIGATE 1000VA/800W,6,NPVD
690,PH 9210,-1,0,1,0,185.35,185.35,0,109.53,0.00,...,NaN,45,NaN,54985,4,NaN,1PE-C001401-00G,FRIGATE 1000VA/800W,6,NPVD
769,PH 9210,-1,0,1,0,113.78,113.78,265,113.78,30152.36,...,NaN,44,NaN,513,8,NaN,1PE-C001401-00G,FRIGATE 1000VA/800W,6,NPVD
817,PH 9210,1,1,0,0,117.57,-117.57,438,117.57,51497.54,...,NaN,2,NaN,516,4,NaN,1PE-C001401-00G,FRIGATE 1000VA/800W,6,NPVD
825,PH 9210,-2,0,2,0,229.74,459.48,423,117.57,49733.92,...,NaN,45,NaN,54985,9,No,1PE-C001401-00G,FRIGATE 1000VA/800W,6,NPVD
827,PH 9210,-2,0,2,0,117.57,235.14,423,117.57,49733.92,...,NaN,2,NaN,527,4,NaN,1PE-C001401-00G,FRIGATE 1000VA/800W,6,NPVD
884,PH 9210,-1,0,1,0,217.36,217.36,240,117.57,28217.83,...,NaN,45,NaN,54985,9,No,1PE-C001401-00G,FRIGATE 1000VA/800W,6,NPVD
1040,PH 9220,-1,0,1,0,350.00,350.00,0,184.77,0.00,...,NaN,22,NaN,54985,4,No,1PE-C001402-00G,FRIGATE 2K,6,NPVD
1041,PH 9220,-1,0,1,0,340.00,340.00,0,184.77,0.00,...,NaN,22,NaN,54985,4,No,1PE-C001402-00G,FRIGATE 2K,6,NPVD
1060,PH 9220,-1,0,1,0,371.18,371.18,0,184.77,0.00,...,NaN,22,NaN,54985,4,No,1PE-C001402-00G,FRIGATE 2K,6,NPVD
1065,PH 9220,-1,0,1,0,371.18,371.18,0,184.77,0.00,...,NaN,22,NaN,54985,4,No,1PE-C001402-00G,FRIGATE 2K,6,NPVD
1151,PH 9220,-1,0,1,0,324.79,324.79,0,139.19,0.00,...,NaN,22,NaN,54985,4,No,1PE-C001402-00G,FRIGATE 2K,6,NPVD
1400,PH 9220,-1,0,1,0,160.21,160.21,99,160.21,15861.41,...,NaN,44,NaN,513,8,NaN,1PE-C001402-00G,FRIGATE 2K,6,NPVD
1401,PH 9220,-1,0,1,0,160.21,160.21,99,160.21,15861.41,...,NaN,44,NaN,513,8,NaN,1PE-C001402-00G,FRIGATE 2K,6,NPVD
1440,PH 9220,-1,0,1,0,322.31,322.31,97,166.23,16125.07,...,NaN,45,NaN,54985,9,No,1PE-C001402-00G,FRIGATE 2K,6,NPVD
1452,PH 9220,-1,0,1,0,322.31,322.31,70,166.23,11636.65,...,NaN,45,NaN,54985,9,No,1PE-C001402-00G,FRIGATE 2K,6,NPVD
1459,PH 9220,-2,0,2,0,323.13,646.26,48,166.23,7979.41,...,NaN,45,NaN,54985,9,No,1PE-C001402-00G,FRIGATE 2K,6,NPVD
1462,PH 9220,-2,0,2,0,166.24,332.48,47,166.23,7813.18,...,NaN,2,NaN,527,4,NaN,1PE-C001402-00G,FRIGATE 2K,6,NPVD
1673,PH 9230,-1,0,1,0,541.15,541.15,0,245.45,0.00,...,NaN,22,NaN,54985,4,No,1PE-C001403-00G,NaN,6,NPVD
1685,PH 9230,-1,0,1,0,541.15,541.15,0,245.45,0.00,...,NaN,22,NaN,54985,4,No,1PE-C001403-00G,NaN,6,NPVD
2180,PH 9230,-1,0,1,0,433.88,433.88,146,222.90,32544.71,...,NaN,45,NaN,54985,9,No,1PE-C001403-00G,NaN,6,NPVD
2191,PH 9230,-3,0,3,0,433.88,1301.64,127,222.90,28309.44,...,NaN,45,NaN,54985,9,No,1PE-C001403-00G,NaN,6,NPVD
2208,PH 9230,-1,0,1,0,432.22,432.22,91,222.90,20284.71,...,NaN,45,NaN,54985,9,No,1PE-C001403-00G,NaN,6,NPVD
2210,PH 9230,-1,0,1,0,222.91,222.91,91,222.90,20284.71,...,NaN,2,NaN,527,4,NaN,1PE-C001403-00G,NaN,6,NPVD
2213,PH 9230,2,2,0,0,222.91,-445.82,89,222.90,19838.90,...,NaN,2,NaN,527,4,NaN,1PE-C001403-00G,NaN,6,NPVD
2215,PH 9230,-3,0,3,0,222.91,668.73,89,222.90,19838.90,...,NaN,2,NaN,527,4,NaN,1PE-C001403-00G,NaN,6,NPVD

In [43]:
df_col = df[['Referencia', 'Codigo Factura', 'Entradas', 'Salidas', 'Fecha Pedido', 'Codigo Pedido', 'Codigo Cliente']]

In [51]:
df_col.loc[df_col['Codigo Factura'].isna()]

,Referencia,Codigo Factura,Entradas,Salidas,Fecha Pedido,Codigo Pedido,Codigo Cliente
277,PH 9210,NaN,0,1,12-09-2019,01/04-A/19-00164,57643
384,PH 9210,NaN,0,1,6-05-2020,01/04-A/20-00119,57643
400,PH 9210,NaN,0,1,28-05-2020,01/04-A/20-00228,57643
402,PH 9210,NaN,0,1,28-05-2020,01/04-A/20-00229,57643
690,PH 9210,NaN,0,1,NaN,NaN,67422
769,PH 9210,NaN,0,1,NaN,NaN,24256
817,PH 9210,NaN,1,0,NaN,NaN,59941
825,PH 9210,NaN,0,2,23-09-2022,01/09-PM/22-01627,66756
827,PH 9210,NaN,0,2,NaN,NaN,67910
884,PH 9210,NaN,0,1,27-12-2022,01/09-PM/22-02271,66756
1040,PH 9220,NaN,0,1,25-02-2019,01/04-A/19-00064,57643
1041,PH 9220,NaN,0,1,25-02-2019,01/04-A/19-00062,57643
1060,PH 9220,NaN,0,1,25-04-2019,01/04-A/19-00097,57643
1065,PH 9220,NaN,0,1,13-05-2019,01/04-A/19-00102,57643
1151,PH 9220,NaN,0,1,26-05-2020,01/04-A/20-00209,57643
1400,PH 9220,NaN,0,1,NaN,NaN,24256
1401,PH 9220,NaN,0,1,NaN,NaN,24256
1440,PH 9220,NaN,0,1,4-08-2022,01/09-PM/22-01372,66756
1452,PH 9220,NaN,0,1,6-09-2022,01/09-PM/22-01515,66756
1459,PH 9220,NaN,0,2,23-09-2022,01/09-PM/22-01627,66756
1462,PH 9220,NaN,0,2,NaN,NaN,67910
1673,PH 9230,NaN,0,1,26-12-2018,01/04-A/18-00171,57643
1685,PH 9230,NaN,0,1,28-01-2019,01/04-A/19-00034,57643
2180,PH 9230,NaN,0,1,18-07-2022,01/09-PM/22-01256,66756
2191,PH 9230,NaN,0,3,4-08-2022,01/09-PM/22-01369,66756
2208,PH 9230,NaN,0,1,20-09-2022,01/09-PM/22-01597,66756
2210,PH 9230,NaN,0,1,NaN,NaN,67910
2213,PH 9230,NaN,2,0,NaN,NaN,67910
2215,PH 9230,NaN,0,3,NaN,NaN,67910