In [2]:
# !pip install pandas

Requirement already satisfied: pandas in c:\users\carlo\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: numpy>=1.18.5 in c:\users\carlo\anaconda3\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\carlo\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\carlo\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\carlo\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [3]:
# importar librerías
import pandas as pd
import numpy as np

In [43]:
# Obtenermos datos de CSV de españa
df = pd.read_csv("./Articulos.csv",sep=";",encoding="latin")

In [44]:
# Renombramos alguna columna
df = df.rename(columns={"Precio coste medio":"Coste Medio"})

In [55]:
df.head(15)

,Codigo Articulo,Nombre Articulo,Coste Medio,Stock,Stock Disponible,Stock Mínimo
0,PH 7010,S.A.I. Phasak trifásica-trifásica 10000 VA Online,0.00,0,0,0
1,PH 7015,S.A.I. Phasak trifásica-trifásica 15000 VA Online,0.00,0,0,0
2,PH 7020,S.A.I. Phasak trifásica-trifásica 20000 VA Online,0.00,0,0,0
3,PH 7030,S.A.I. Phasak trifásica-trifásica 30000 VA Online,0.00,0,0,0
4,PH 7040,S.A.I. Phasak trifásica-trifásica 40000 VA Online,0.00,0,0,0
5,PH 7060,S.A.I. Phasak trifásica-trifásica 60000 VA Online,0.00,0,0,0
6,PH 7062,Bateria suplementar (40bat64Amp) para PH 7060,0.00,0,0,0
7,PH 7080,S.A.I. Phasak trifásica-trifásica 80000 VA Online,0.00,0,0,0
8,PH 7100,S.A.I. Phasak trifásica-trifásica 100000 VA On...,0.00,0,0,0
9,PH 7120,S.A.I. Phasak trifásica-trifásica 120000 VA On...,0.00,0,0,0
10,PH 7210,S.A.I. Phasak OTTIMA 1060VA Interactive,36.17,183,153,180
11,PH 7266,S.A.I. Phasak OTTIMA 660VA Interactive,20.81,1351,1347,1073
12,PH 7288,S.A.I. Phasak OTTIMA 860VA Interactive,26.66,49,49,485
13,PH 7312,S.A.I. Phasak SIRIUS 1260VA Interactive,45.00,597,596,299
14,PH 7312-RA+,"S.A.I. Phasak SIRIUS Recondicionado ""Grado A+""...",37.46,0,0,0

In [68]:
# Comprobamos si hay datos nulos
df.isna().sum()

Codigo Articulo     0
Nombre Articulo     0
Coste Medio         0
Stock               0
Stock Disponible    0
Stock Mínimo        0
dtype: int64

In [48]:
# Reemplazamos las , por . en los decimales.
df["Coste Medio"] = df["Coste Medio"].str.replace(',','.')

In [56]:
df.head(15)

,Codigo Articulo,Nombre Articulo,Coste Medio,Stock,Stock Disponible,Stock Mínimo
0,PH 7010,S.A.I. Phasak trifásica-trifásica 10000 VA Online,0.00,0,0,0
1,PH 7015,S.A.I. Phasak trifásica-trifásica 15000 VA Online,0.00,0,0,0
2,PH 7020,S.A.I. Phasak trifásica-trifásica 20000 VA Online,0.00,0,0,0
3,PH 7030,S.A.I. Phasak trifásica-trifásica 30000 VA Online,0.00,0,0,0
4,PH 7040,S.A.I. Phasak trifásica-trifásica 40000 VA Online,0.00,0,0,0
5,PH 7060,S.A.I. Phasak trifásica-trifásica 60000 VA Online,0.00,0,0,0
6,PH 7062,Bateria suplementar (40bat64Amp) para PH 7060,0.00,0,0,0
7,PH 7080,S.A.I. Phasak trifásica-trifásica 80000 VA Online,0.00,0,0,0
8,PH 7100,S.A.I. Phasak trifásica-trifásica 100000 VA On...,0.00,0,0,0
9,PH 7120,S.A.I. Phasak trifásica-trifásica 120000 VA On...,0.00,0,0,0
10,PH 7210,S.A.I. Phasak OTTIMA 1060VA Interactive,36.17,183,153,180
11,PH 7266,S.A.I. Phasak OTTIMA 660VA Interactive,20.81,1351,1347,1073
12,PH 7288,S.A.I. Phasak OTTIMA 860VA Interactive,26.66,49,49,485
13,PH 7312,S.A.I. Phasak SIRIUS 1260VA Interactive,45.00,597,596,299
14,PH 7312-RA+,"S.A.I. Phasak SIRIUS Recondicionado ""Grado A+""...",37.46,0,0,0

In [50]:
# Pasamos el Coste medio a decimal
df["Coste Medio"] = df["Coste Medio"].astype('float')

In [51]:
df.dtypes

Codigo Articulo      object
Nombre Articulo      object
Coste Medio         float64
Stock                 int64
Stock Disponible      int64
Stock Mínimo          int64
dtype: object

In [57]:
# Asignamos la columna Codigo como indice del DataFrame
dfi = df.set_index("Codigo Articulo")

In [59]:
dfi.head()

,Nombre Articulo,Coste Medio,Stock,Stock Disponible,Stock Mínimo
Codigo Articulo,,,,,
PH 7010,S.A.I. Phasak trifásica-trifásica 10000 VA Online,0.0,0,0,0
PH 7015,S.A.I. Phasak trifásica-trifásica 15000 VA Online,0.0,0,0,0
PH 7020,S.A.I. Phasak trifásica-trifásica 20000 VA Online,0.0,0,0,0
PH 7030,S.A.I. Phasak trifásica-trifásica 30000 VA Online,0.0,0,0,0
PH 7040,S.A.I. Phasak trifásica-trifásica 40000 VA Online,0.0,0,0,0

In [65]:
dfi.loc[dfi['Coste Medio']>0]

,Nombre Articulo,Coste Medio,Stock,Stock Disponible,Stock Mínimo
Codigo Articulo,,,,,
PH 7210,S.A.I. Phasak OTTIMA 1060VA Interactive,36.17,183,153,180
PH 7266,S.A.I. Phasak OTTIMA 660VA Interactive,20.81,1351,1347,1073
PH 7288,S.A.I. Phasak OTTIMA 860VA Interactive,26.66,49,49,485
PH 7312,S.A.I. Phasak SIRIUS 1260VA Interactive,45.00,597,596,299
PH 7312-RA+,"S.A.I. Phasak SIRIUS Recondicionado ""Grado A+""...",37.46,0,0,0
...,...,...,...,...,...
PHO 8137,"Armario rack 19"" Phasak Pro 37U 800x1000 negro",318.51,0,0,0
PHO 8142,"Armario rack 19"" Phasak Pro 42U 800x1000 negro",349.92,0,0,0
PHO 8147,"Armario rack 19"" Phasak Pro 47U 800x1000 negro",369.73,0,0,0
PHO 8837,"Armario rack 19"" Phasak Pro 37U 800x 800 negro",227.45,0,0,0
PHO 8842,"Armario rack 19"" Phasak Pro 42U 800x 800 negro",392.42,1,1,0

In [67]:
dfi.isna().sum()

Nombre Articulo     0
Coste Medio         0
Stock               0
Stock Disponible    0
Stock Mínimo        0
dtype: int64

In [69]:
dfi.describe()

       Coste Medio         Stock  Stock Disponible  Stock Mínimo
count   350.000000    350.000000        350.000000    350.000000
mean    112.015229    163.308571        161.291429     35.714286
std     274.019611    799.156810        791.289427    145.821135
min       0.000000      0.000000        -10.000000      0.000000
25%       2.227500      0.000000          0.000000      0.000000
50%      26.580000      3.000000          3.000000      1.000000
75%     109.552500     21.000000         21.000000      8.000000
max    2758.430000  10000.000000       9940.000000   1500.000000

In [ ]:
dfi.[]